namespace: postgre-chart

resources:
- namespace.yaml

helmCharts:
- name: postgresql
  namespace: postgre-chart
  valuesFile : ./my-values.yaml
  repo: https://charts.bitnami.com/bitnami
  version: 13.2.24
  releaseName: my-postgre-release
  IncludeCRDs: true

